In [1]:
import numpy as np

# Excercise 3

Given two matrix of intergers of same shape. Find a boolean matrix and 0,1 matrix which represents which of the elements are equal at any index in both matrix

    Input
    [[2 2 1 1 2]
     [1 2 2 1 2]
     [2 3 1 2 1]
     [3 1 3 1 1]
     [1 3 1 3 3]]

    [[2 1 1 3 2]
     [3 2 2 2 2]
     [3 2 1 3 3]
     [3 2 1 2 2]
     [1 3 2 2 3]]
     
    Output
    [[ True False  True False  True]
     [False  True  True False  True]
     [False False  True False False]
     [ True False False False False]
     [ True  True False False  True]]
     
     [[0 1 0 1 0]
     [1 0 0 1 0]
     [1 1 0 1 1]
     [0 1 1 1 1]
     [0 0 1 1 0]]

In [13]:
input1 = np.random.randint(0,4,25).reshape([5,5])
input1

array([[1, 0, 0, 3, 2],
       [1, 1, 0, 0, 0],
       [1, 3, 2, 0, 1],
       [3, 1, 0, 0, 1],
       [2, 0, 2, 2, 3]])

In [14]:
input2 = np.random.randint(0,4,25).reshape([5,5])
input2

array([[3, 1, 2, 0, 3],
       [3, 1, 1, 2, 2],
       [2, 3, 2, 2, 3],
       [3, 2, 3, 0, 2],
       [3, 0, 1, 1, 3]])

In [16]:
output = [input1 == input2]
output

[array([[False, False, False, False, False],
        [False,  True, False, False, False],
        [False,  True,  True, False, False],
        [ True, False, False,  True, False],
        [False,  True, False, False,  True]], dtype=bool)]

In [23]:
output1 = np.zeros([5,5], dtype=np.int16)
#convert False = 0 and True = 1

In [24]:
dc = np.array(input1==input2, dtype=np.int16)
dc

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 1, 0, 0],
       [1, 0, 0, 1, 0],
       [0, 1, 0, 0, 1]], dtype=int16)

In [3]:
a = np.random.randint(0,4,[4,4], dtype=np.int32)
b = np.random.randint(0,4,[4,4], dtype=np.int32)

In [23]:
c = np.zeros([4,4], dtype=np.int32)

In [26]:
c[a==b] = 1

In [27]:
c

array([[1, 1, 0, 0],
       [0, 0, 1, 1],
       [0, 1, 0, 0],
       [1, 1, 1, 1]])