In [3]:
import numpy as np

# Excercise 1

Swap two rows of an array

    input
    
    [[ 0  1  2  3  4]
     [ 5  6  7  8  9]
     [10 11 12 13 14]
     [15 16 17 18 19]
     [20 21 22 23 24]]
    
    output
    [[ 5  6  7  8  9]
     [ 0  1  2  3  4]
     [10 11 12 13 14]
     [15 16 17 18 19]
     [20 21 22 23 24]]

In [18]:
input = np.arange(25).reshape([5,5])

In [19]:
input[:2:,:] = input[1::-1,:]
input

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
input[:2:1,]

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [35]:
input[1::-1]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])