In [1]:
import numpy as np

# Excercise 2

Row vector to column vector

    input
    [ 0  1  2  3  4  5]
    
    output
    [[0]
     [1]
     [2]
     [3]
     [4]
     [5]]

In [3]:
input = np.arange(6)
output = np.reshape(input, [-1,1])
output

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [4]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [10]:
a.reshape([-1,1])

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])