In [9]:
import numpy as np

# Excercise 6

Generate following sequences using numpy

*Sequence 1:*

    [[ 1  1  1  1  1  1  1  1  1  1]
     [ 1  2  2  2  2  2  2  2  2  2]
     [ 1  2  3  3  3  3  3  3  3  3]
     [ 1  2  3  4  4  4  4  4  4  4]
     [ 1  2  3  4  5  5  5  5  5  5]
     [ 1  2  3  4  5  6  6  6  6  6]
     [ 1  2  3  4  5  6  7  7  7  7]
     [ 1  2  3  4  5  6  7  8  8  8]
     [ 1  2  3  4  5  6  7  8  9  9]
     [ 1  2  3  4  5  6  7  8  9 10]]

*Sequence 2:*

    [[ 1  2  3  4  5  6  7  8  9 10]
     [ 2  3  4  5  6  7  8  9 10 11]
     [ 3  4  5  6  7  8  9 10 11 12]
     [ 4  5  6  7  8  9 10 11 12 13]
     [ 5  6  7  8  9 10 11 12 13 14]
     [ 6  7  8  9 10 11 12 13 14 15]
     [ 7  8  9 10 11 12 13 14 15 16]
     [ 8  9 10 11 12 13 14 15 16 17]
     [ 9 10 11 12 13 14 15 16 17 18]
     [10 11 12 13 14 15 16 17 18 19]]

In [34]:
def pattern1():
    a = np.ones([10,10], dtype=np.int16)
    for i in range(9):
        a[i+1:, i+1:] = a[i+1, i+1]+1
    print(a)

In [35]:
pattern1()

[[ 1  1  1  1  1  1  1  1  1  1]
 [ 1  2  2  2  2  2  2  2  2  2]
 [ 1  2  3  3  3  3  3  3  3  3]
 [ 1  2  3  4  4  4  4  4  4  4]
 [ 1  2  3  4  5  5  5  5  5  5]
 [ 1  2  3  4  5  6  6  6  6  6]
 [ 1  2  3  4  5  6  7  7  7  7]
 [ 1  2  3  4  5  6  7  8  8  8]
 [ 1  2  3  4  5  6  7  8  9  9]
 [ 1  2  3  4  5  6  7  8  9 10]]


In [36]:
def pattern2():
    a = np.zeros([10,10], dtype==np.int16)
    for i in range(9):
        