In [1]:
import numpy as np

# Excercise 4

Given an array with 4 categories:

1. Create one hot matrix from array
2. Create array back using one hot matrix

Input:  

    [3 4 3 4 0 3 2 4 1 0]

Output 1:   

    [[0 0 0 1 0]
     [0 0 0 0 1]
     [0 0 0 1 0]
     [0 0 0 0 1]
     [1 0 0 0 0]
     [0 0 0 1 0]
     [0 0 1 0 0]
     [0 0 0 0 1]
     [0 1 0 0 0]
     [1 0 0 0 0]]
 
Output 2:

    [3 4 3 4 0 3 2 4 1 0]

In [30]:
input1 = np.array([3, 4, 3, 4, 0, 3, 2, 4, 1, 0])
input1

array([3, 4, 3, 4, 0, 3, 2, 4, 1, 0])

In [31]:
temp = np.zeros([input1.shape[0], np.max(input1)+1], dtype=np.int16)
temp

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int16)

In [18]:
'''for x in range(len(input1)):
    temp[x, input1[x]]=1
temp
'''

array([[0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0]], dtype=int16)

In [34]:
temp[range(10), input1] = 1
temp

array([[0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0]], dtype=int16)